name: flutter_base
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  async: ^2.13.0
  device_preview: ^1.2.0
  firebase_analytics: ^12.0.0
  firebase_core: ^4.0.0
  firebase_crashlytics: ^5.0.0
  flutter:
    sdk: flutter
  flutter_flavor: ^3.1.4
  flutter_launcher_icons: ^0.14.4
  flutter_localizations:
    sdk: flutter
  form_validation: ^3.2.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  hive_test: ^1.0.1
  husky: ^0.1.7
  intl: ^0.20.2
  intl_utils: ^2.8.8
  melos: ^6.3.3
  network_image_mock: ^2.1.1
  package_info_plus: ^8.3.0
  permission_handler: ^12.0.1
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  total_lints: ^3.6.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3


flutter:
  uses-material-design: true

